### ISSUE TITLE
Changes in HDF5 breaking build

### ISSUE THREAD

**Issue by skn123** [garrison/eigen3-hdf5#11]
The current HDF5 trunk does not have some functions (like Attribute) in the C++ class. As a result the code is not building. We can revert back to older versions, but apparently those libraries are causing other projects to crash from a severe memory leak! Any thoughts?
Specifically this function is where the code starts failing to compile
`
template <typename T>
void save_scalar_attribute (const H5::H5Location &h5obj, const std::string &name, const T &value)
{
    const H5::DataType * const datatype = DatatypeSpecialization<T>::get();
    H5::DataSpace dataspace(H5S_SCALAR);
    H5::Attribute att = h5obj.createAttribute(name, *datatype, dataspace);
    att.write(*datatype, &value);
}
`
Apparently, createAttribute is not there in the H5Location

**Comment by garrison** [comment]
Is there a released version of HDF5 for which the code fails, or is it only trunk?  If you don't need attributes I suppose the simple thing would be to remove those portions of the header file.  I no longer use this library myself anymore so I don't expect I will fix it, but I'd be happy to merge a pull request that fixes things.

**Comment by garrison** [comment]
Thanks for the report.  The latest `main` branch should fix this problem; feel free to re-open if not.
