### ISSUE TITLE
over write issue 

### ISSUE THREAD

**Issue by jdily** [garrison/eigen3-hdf5#2]
Hi, thx for the great library!
I have found out that if there is an existing file with the same name, it will not overwrite the file.
I am wondering if there are method to deal with this?
Or there is some flags that I should select properly..?

thx!

**Comment by garrison** [comment]
Do you open the file as the README says, with `H5::H5File file("filename1.h5", H5F_ACC_TRUNC);`?  The flag `H5F_ACC_TRUNC` should truncate any existing file with the same name.

**Comment by garrison** [comment]
I am closing this, but please let me know if you have any further issues.
